openapi: 3.0.3

info:
  title: Event Planning App RESTful API Project
  version: "1.0"
  description: The Event Planning App RESTful API Project is an application used for creating and managing events.
  contact:
    name: Developer 
    email: dimas.yudhana@gmail.com
    url: https://github.com/dimasyudhana
  license:
    name: APACHE 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

externalDocs:
  description: Visit the Event Planning App GitHub repository for more information.
  url: https://github.com/wanta-zulfikri/Event-Planning-App.git

servers:
  - url: https://{environment}.eventplanningapp.com/api/v1
    description: "Event Planning App RESTful API Servers"
    variables:
      environment:
        enum:
          - deployment
          - localhost:8080
        default: localhost:8080
  - url: https://deployment.eventplanningapp.com/api/v1
    description: "Production server"
  - url: https://localhost:8000/
    description: "Local development server"

paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Register new user
      description: Endpoint register new user to the database
      requestBody:
      #  $ref: '#/components/requestBodies/RequestRegisterUser'
      responses:
        '200':
          # $ref: '#/components/responses/Response200'  
        '400':
          # $ref: '#/components/responses/Response400'
        '500':
          # $ref: '#/components/responses/Response500'
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login user
      description: Endpoint login user to the web-application
      requestBody: 
        #  $ref: '#/components/requestBodies/RequestLoginUser'
      responses:
        '200':
        #  $ref: '#/components/responses/Response200'
        '400':
         # $ref: '#/components/responses/Response400'
        '500':
        #  $ref: '#/components/responses/Response500'


  ####################################
  #  Events
  ####################################

  /Events:
    get:
      tags:
        - Event
      summary: List all Event 
      responses:
        200:
          description: "Get all Event"
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/EventSchemaGetallEvent"
              example:
                data:
                  [
                    {
                      "name": "Webinar: Your Product Manager Career by PlayStation Sr PM",
                      "hosted_by": "Product School",
                      "date": "2023-04-14T15:59:21.150Z",
                      "location": "Jakarta",
                      "details": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                      "event_picture": "https://kurabsent.s3.amazonaws.com/2022-07-06%2006%3A40%3A47.jpg",
                    },
                    {
                      "name": "udemy: golang goroutines",
                      "hosted_by": "Product Udemy",
                      "date": "2023-04-15T15:59:21.150Z",
                      "location": "Jakarta",
                      "details": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                      "event_picture": "https://kurabsent.s3.amazonaws.com/2022-07-06%2006%3A40%3A47.jpg",
                    },
                    {
                      "name": "hackerrank: golang goroutines",
                      "hosted_by": "Product Udemy",
                      "date": "2023-04-15T15:59:21.150Z",
                      "location": "Jakarta",
                      "details": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                      "event_picture": "https://kurabsent.s3.amazonaws.com/2022-07-06%2006%3A40%3A47.jpg",
  
                    },
                  ]
                message: "success show all event"
        