on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/be16:latest 
      - 
        name: multiple command
        uses: appleboy/ssh-action@v0.1.9
        with:
          port: ${{ secrets.PORT }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker stop ${{ secrets.CNAME }}
            docker rm ${{ secrets.CNAME }}
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/be16:latest
            docker run --name ${{ secrets.CNAME }} -d -p 8080:8000 --link="databook" -e DB_USER=${{ secrets.DBUSER }} -e DB_PASS=${{ secrets.DBPASS }} -e DB_HOST=${{ secrets.DBHOST }} -e DB_PORT=${{ secrets.DBPORT }} -e DB_NAME=${{ secrets.DBNAME }} -e JWT_KEY=${{ secrets.JWT_KEY }} -e CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} -e CLOUDINARY_UPLOAD_FOLDER=${{ secrets.CLOUDINARY_UPLOAD_FOLDER }} ${{ secrets.DOCKERHUB_USERNAME }}/be16:latest
